# Test environment configurations

# Custom configurations

link:
  defaultlink: "http://localhost:7003"
  service1: "http://localhost:7001/engine?engineType="
  service2: "http://localhost:7002/luxury?performanceType="
